os:
  - linux

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- wget https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
- sudo dpkg -i pandoc-2.1.3-1-amd64.deb

script:
  - "export PDF_OUTPUT=$(grep index.md -e '^generated_file: '  | sed -e 's/generated_file: //' -e 's/ //g')"
  - mkdir _out
  - make build OUTPUT="_out/$PDF_OUTPUT"

deploy:
  local-dir: _out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master-pdf
  on:
    branch: master
